### PR TITLE
Add a few properties. 

### PR DESCRIPTION
**Pull request by hound22**
Changes made:
1. Added 'Can pickup items' property.
2. Edited a few descriptions and added some that didn't have one.

### CODE REVIEW

**Comment by hound22** [comment]
Changes added:
- Added a new block property 'Requires Silk Touch'.

**Comment by hound22** [comment]
Changes added:

Added the new entity property 'Persistency'.

**Comment by hound22** [comment]
Changes:

Add a new item property 'Renewable'.
Update a few banner pattern names.

**Comment by hound22** [comment]
Changes:

- Add 1.20 items and their item ids.

**Comment by hound22** [comment]
Changes:

- Add a new block property 'Intended Tool'.

**Comment by hound22** [comment]
Changes:

- Add a new entity property 'Xp Dropped'.

**Comment by hound22** [comment]
Changes:
- Add a new block property 'Xp Dropped When Mined'.

**Comment by JoakimThorsen** [comment]
I've skimmed through this now, and it mostly looks good, only thing I'd want to hold off on is the addition of all the new items. Given that all the existing item properties haven't been updated to account for these new additions, they would instead be listed under the default value, which would make the data unreliable. Would you mind withholding these changes for now so I can merge the rest?

Really good work :)

**Comment by hound22** [comment]
Sounds good, they have been withheld.

Changes:
- Temporarily removed 1.20 items and their item IDs.

**Pull request merged**
